name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install bats
      run: sudo apt-get install bats
    - name: Run bats tests
      run: |
        bash ./test.sh
